[package]
name = "chip8-oxidized"
version = "1.0.0"
authors = ["valentinpi, Kaneki-kun9"]
edition = "2018"

[dependencies]
rand = "0.7.3"
sdl2 = { version = "0.34", features = ["bundled", "static-link"] }

[[bin]]
name = "chip8-oxidized"
path = "src/main.rs"
