[package]
name = "chip8-oxidized-web"
version = "0.1.0"
authors = ["valentinpi <valentinpickel@gmx.de>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
wasm-bindgen = "0.2.63"

[lib]
crate-type = ["cdylib"]
name = "chip8oxidizedweb"
path ="../src/schip8.rs"
